name: Run Flask Backend

on:
  push:
    branches: [ "main" ]

jobs:
  run-backend:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Flask backend (test only)
        run: |
          python main.py &
          sleep 3
          curl http://localhost:5000
